
server:
  port: 8769
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: zuul
zuul:
  routes:
    feign:
      path: /api-a/**
      serviceId: feign

