server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  sleuth:
    sampler:
      probability: 1
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/191108?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
  application:
    name: provider
mybatis:
  configuration:
    map-underscore-to-camel-case: true  #驼峰命名
  mapper-locations: classpath:*.xml